import { Metadata } from "next";
import SignUpForm from "./signUpForm";

export const metadata: Metadata = {
  title: "Warm Wood Homes | Sign Up",
  description: "Generated by create next app",
};

export default function SignInPage() {
  return <SignUpForm></SignUpForm>;
}
