import { Metadata } from "next";
import SignInForm from "./signInForm";

export const metadata: Metadata = {
  title: "Warm Wood Homes | Sign In",
  description: "Generated by create next app",
};

export default function SignInPage() {
  return <SignInForm></SignInForm>;
}
